-- Up Migration
CREATE SCHEMA IF NOT EXISTS media;
CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS interaction;
CREATE SCHEMA IF NOT EXISTS auth;

-- Down Migration
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS interaction CASCADE;
DROP SCHEMA IF EXISTS users CASCADE;
DROP SCHEMA IF EXISTS media CASCADE;
